theme: jekyll-theme-cayman
title: BIT-Key, Bridging Business and IT, stuff we learned
description: This site contains useful links to things we found on the web or had to find out ourselves.

show_downloads: "false"
